import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'SubScribe',
  description: 'Generated by create-wagmi',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}